# -*- coding: utf-8 -*-
"""5.7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oq-tl6qo8IfLzWzsPxjcMyqM4SdOBiK7

## Importação de bibliotecas
"""

# Importação das bibliotecas necessarias
import pandas as pd

"""## Carregamento e limpeza dos dados"""

#1 Carregando dados CSV
df_ovni = pd.read_csv('https://raw.githubusercontent.com/oliveirafhm/data_science/master/OVNIS.csv')
df_ovni

#2 Removendo os dados vazios da coluna City, Shape e State
                                                                                              # df_ovni = df_ovini.dropna() -> Comando para deletando todos os valores vazios do Dataframe
df_ovni = [df_ovni['City'].notna()]
df_ovni = [df_ovni['State'].notna()]
df_ovni = [df_ovni['Shape'].notna()]

#3 Mantendo somente os estados dos estados Unidos 
# Carregando dados com estados somente dos estados unidos 
df_states_usa = pd.read_csv('https://raw.githubusercontent.com/oliveirafhm/data_science/master/usa_states.csv') 
df_ovni['State']

filtro2 = []
for reg in list(df_ovni['State']):
  if reg in list(df_states_usa['Abbreviation']):
    filtro2.append(True)
  else:
    filtro2.append(False)
df_ovni = df_ovni[filtro2]
# Amostra filtrada somente com estados dos 'Estados Unidos'
df_ovni

# 4 Removendo colunas irrelevantes 'Duration' , 'Summary' && 'Posted'
df = df_ovni.drop(['Duration','Summary','Posted'],axis=1)
df

"""## Visualização dos Shapes Limpos"""

# 5 Mostrando somente o registro Shapes mais populares > que 1000 ocorrencias
shape = df['Shape'].value_counts()

# Resetar o índice do Df
shape = shape.reset_index()

# Colocando os valores de índice populares > 1000
shape_popular =  shape[shape['Shape']>1000] ['index']
shape_popular

"""## Salvando o DataFrame em arquivo CSV"""

# Salvar o 'Df' com os dados limpos 
shape_popular.to_csv('df_OVINI_limpo.csv')