# -*- coding: utf-8 -*-
"""5.7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oq-tl6qo8IfLzWzsPxjcMyqM4SdOBiK7

## Importação de bibliotecas
"""

# Importação das bibliotecas necessarias
import pandas as pd

"""## Carregamento e limpeza dos dados"""

#1 Carregando dados CSV
df_ovni = pd.read_csv('https://raw.githubusercontent.com/oliveirafhm/data_science/master/OVNIS.csv')
df_ovni


"""## Salvando o DataFrame em arquivo CSV"""

# Salvar o 'Df' com os dados limpos 
shape_popular.to_csv('df_OVINI_limpo.csv')

# Fim