# -*- coding: utf-8 -*-
"""5.8 Acréscimos de variaveis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ePfJ8MWUqDOXLgkDcBazD7pGAOTrgN5v

## Import DataFrame limpo
"""

import pandas as pd
import datetime

#1 Carregando DataFrame limpo

df = pd.read_csv('df_OVNI_limpo.csv')

#2 Separar a coluna 'data' e 'hora' do mesmo DataFrame

# Dividir o conteúdo da coluna Date / Time em duas novas colunas no mesmo dataframe e deletar a coluna Date / Time .
                                                                                                                            # DataFrame = 'df'. Estou selecionando a coluna 'Date / Time', acessando a função str e split para separar a coluna, com a separação realizada renomeio as colunas'Sight_Date','Sight_Time' com a Data e Hora devidamente separadas
df1 = df.join(df['Date / Time'].str.split(' ', 1, expand=True).rename(columns={0:'Sight_Date', 1:'Sight_Time'}))
df1
# Excluindo a coluna [Date / Time]
df1.drop(['Date / Time'], inplace=True, axis= 1)
df1

"""### teste"""

df2 =df1


#3 Separando dias e colunas
# 0 é segunda e 6 é domingo
#! apt install locales-all
#!locale -a
locale.setlocale(locale.LC_ALL, 'pt_PT.utf8')

df2 = pd.date_range('1997-01-29', '2017-01-12', freq='D').to_series()
df2.dt.day_name()
#df1.day_name(

weekday_ptbr = {
    'Monday': 'Segunda-feira',
    'Tuesday': 'Terça-feira',
    'Wednesday': 'Quarta-feira',
    'Thursday': 'Quinta-feira',
    'Friday': 'Sexta-feira',
    'Saturday': 'Sábado',
    'Sunday': 'Domingo'
}



'''
idx = pd.date_range(start='2018-01-01', freq='D', periods=3)
 idx
DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03'],
              dtype='datetime64[ns]', freq='D')
idx.day_name()
Index(['Monday', 'Tuesday', 'Wednesday'], dtype='object')

'''

"""# CERTO"""

#3 Separando dias e colunas
df1['sight_weekday'] = pd.to_datetime(df1['Sight_Date'])
df1['sight_weekday'] = df1['sight_weekday'].dt.weekday_name

weekday_ptbr = {
    'Monday': 'Segunda-feira',
    'Tuesday': 'Terça-feira',
    'Wednesday': 'Quarta-feira',
    'Thursday': 'Quinta-feira',
    'Friday': 'Sexta-feira',
    'Saturday': 'Sábado',
    'Sunday': 'Domingo'
}

df1 = df1.replace({'sight_weekday': weekday_ptbr})

df1.head()

"""## Separando as variaveis Mes e Dia"""

#4 Separação de variaveis mes e dia 

df1['sight_Day']=pd.to_datetime(df1['Sight_Date']).dt.day
df1['sight_Month']=pd.to_datetime(df1['Sight_Date']).dt.month

df1

"""## Criando dataFrame com as Alterações feitas"""

#5 Criando novo arquivo (.csv) com as alterações feitas
df1.to_csv('df_OVNI_preparado.csv')