# -*- coding: utf-8 -*-
"""5.7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oq-tl6qo8IfLzWzsPxjcMyqM4SdOBiK7


"""## Visualização dos Shapes Limpos"""

# 5 Mostrando somente o registro Shapes mais populares > que 1000 ocorrencias
shape = df['Shape'].value_counts()

# Resetar o índice do Df
shape = shape.reset_index()

# Colocando os valores de índice populares > 1000
shape_popular =  shape[shape['Shape']>1000] ['index']
shape_popular

# ...